version: '3'
services:
  php-apache:
    build:
      context: ./php-apache
    ports:
      - 80:80
    volumes:
      - ./DocumentRoot:/var/www/html
    links:
      - mariadb

  mariadb:
    image: mariadb:10.1
    volumes:
        - mariadb:/var/lib/mysql
    environment:
        TZ: "Europe/Rome"
        MYSQL_ROOT_PASSWORD: "rootpwd"
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'pwd'
        MYSQL_DATABASE: 'testdb'

volumes:
    mariadb: